
const x = 10

// checar se x é um número
try {
    x =2 
} catch (err) {
    console.log(`Erro: ${err}`)
}

console.log('Continuando o código...')


