
const x = 10

// vai tentar atribuir um novo número a uma constante(o que não pode)
try {
    x = 2 
} catch (err) {
    console.log(`Erro: ${err}`)
}

console.log('Continuando o código...')


